### PR TITLE
Upgrade to filament 3.x

### PR DESCRIPTION
**Pull request by a21ns1g4ts**

### CODE REVIEW

**Review by widiu7omo — COMMENTED** [review]
Ok. Thanks

**Comment by a21ns1g4ts** [comment]
@widiu7omo It is an draft please revert :smiling_face_with_tear:

**Comment by a21ns1g4ts** [comment]
@widiu7omo lack bulk actions

**Comment by a21ns1g4ts** [comment]
@widiu7omo ok.. tomorow i will send an pr to upgrade bulk actions :ok_man:

**Pull request merged**
